### ISSUE TITLE
Online Demo for the Online Image Processing Journal not working

### ISSUE THREAD

**Issue by wenruiliau** [Mirebeau/HamiltonFastMarching#8]
In the Markdown description of the repository, there is a link to an online demo [here](http://ipol-geometry.loria.fr/~kerautre/ipol_demo/DemoIPOL_LORIA-Geom_HFM/)

The link appears to be broken.

**Comment by Mirebeau** [comment]
Fixed. (new address : http://ipol-geometry.loria.fr/~kerautre/ipol_demo/DemoIPOL_HFM/)
Thanks for the feedback.
