### ISSUE TITLE
A error about Install HFM

### ISSUE THREAD

**Issue by orangeqqq** [Mirebeau/HamiltonFastMarching#9]
Dear @Mirebeau ,

Thanks for sharing the great work. 

However, I had a problem when I run the example of notebook 'AdaptiveGridDiscretizations/Notebooks_FMM/Isotropic.ipynb'.

I have installed agd and hfm successfully by conda. 

<img src="https://user-images.githubusercontent.com/46962407/146940265-e93bc15f-cc51-4514-b753-c6ec342de2cf.png" width="600" height = "350">

But the notebook have a error.
<img src="https://user-images.githubusercontent.com/46962407/146941255-b5e520ad-927e-4994-bb18-4025b54e498b.png" width="600" height = "350">

```python
ModuleNotFoundError                       Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_8824/453514078.py in <module>
----> 1 hfmOut = hfmIn.Run()

E:\githubl\pymic\AdaptiveGridDiscretizations\AdaptiveGridDiscretizations-master\Notebooks_FMM\..\agd\Eikonal\DictIn.py in Run(self, join, **kwargs)
    264                         else: return dictOut(out)
    265 
--> 266                 if   self.mode=='cpu': return to_dictOut(run_detail.RunSmart(self,**kwargs))
    267                 elif self.mode=='cpu_raw': return to_dictOut(run_detail.RunRaw(self.store,**kwargs))
    268                 elif self.mode=='cpu_transfer':

E:\githubl\pymic\AdaptiveGridDiscretizations\AdaptiveGridDiscretizations-master\Notebooks_FMM\..\agd\Eikonal\run_detail.py in RunSmart(hfmIn, co_output, cache, returns)
    151         # Call to the HFM library
    152         if returns=='in_raw': return hfmIn_raw
--> 153         hfmOut_raw = RunDispatch(hfmIn_raw,GetBinaryDir("FileHFM","HFMpy"))
    154         if returns=='out_raw': return hfmOut_raw
    155 

E:\githubl\pymic\AdaptiveGridDiscretizations\AdaptiveGridDiscretizations-master\Notebooks_FMM\..\agd\Eikonal\LibraryCall.py in RunDispatch(params, bin_dir)
     52         if bin_dir is None:
     53                 moduleName = 'HFMpy.HFM_'+modelName
---> 54                 HFM = importlib.import_module(moduleName)
     55                 hfm = HFM.HFMIO()
     56                 SetInput(hfm,params)

E:\app\anaconda\envs\torchgpu\lib\importlib\__init__.py in import_module(name, package)
    125                 break
    126             level += 1
--> 127     return _bootstrap._gcd_import(name[level:], package, level)
    128 
    129 

E:\app\anaconda\envs\torchgpu\lib\importlib\_bootstrap.py in _gcd_import(name, package, level)

E:\app\anaconda\envs\torchgpu\lib\importlib\_bootstrap.py in _find_and_load(name, import_)

E:\app\anaconda\envs\torchgpu\lib\importlib\_bootstrap.py in _find_and_load_unlocked(name, import_)

ModuleNotFoundError: No module named 'HFMpy.HFM_Isotropic2'
```

then I find that I can import HFMpy ,but  the python can not import module.
![屏幕截图 2021-12-21 124015](https://user-images.githubusercontent.com/46962407/146922811-01ac6f28-da2c-43eb-9f19-662ba3665c69.png)

my system is  windows 10. 

Could you tell me how should i deal with the problem?

Looking forward to your reply.

Best regards,

Yuntao

**Comment by Mirebeau** [comment]
Thanks for the bug report, I'll look into it asap.

In the meantime, as a quick fix, you can use the GPU accelerated solver by uncommenting the following line in section 0.1 of the notebook. 

<<<
from agd import AutomaticDifferentiation as ad; plt,quiver,Eikonal = map(ad.cupy_friendly,(plt,quiver,Eikonal))
>>>

**Comment by Mirebeau** [comment]
The problem is that the HFMpy binaries (CPU eikonal solver) are compiled for python 3.7 (tested) and 3.8, but not for python 3.9. 

I need to compile new binaries to support the recent python versions, but Travis-ci which was used until now does not support free plans anymore, hence a migration is needed.

So the options right now are (choose one) : 
- use the GPU eikonal solver, see previous comment
- use the CPU eikonal solver, compiled locally on your machine, as described in https://github.com/Mirebeau/HamiltonFastMarching
- use the CPU eikonal solver, with Python 3.7 (tested) or 3.8

**Comment by orangeqqq** [comment]
Thank you
